### ISSUE TITLE
LINK : fatal error LNK1104: cannot open file 'LIBCMT.lib'

### ISSUE THREAD

**Issue by dalinwanglhtz** [thepaul/libjna-java#2]
Hi,

I'm trying to build it with Ant into jar files to be used by my other project. But stuck on getting libffi working. See issue below raised:

https://github.com/libffi/libffi/issues/538

Not sure if anyone can help here. 

Compile error attached here:
[ant_compile_error.txt](https://github.com/thepaul/libjna-java/files/4138049/ant_compile_error.txt)

Cheers
Dale

**Comment by thepaul** [comment]
Hi. This project was solely for making some specialized Debian packaging to the Java JNA library, and is probably not helpful to what you're doing now. In particular, this project is 9 years out of date.

You probably want https://github.com/java-native-access/jna instead.
